### ISSUE TITLE
 ethereum-oasis / baseline-roadmap 

### ISSUE THREAD

**Issue by michaelachrisco** [michaelachrisco/Electronic-Interchange-Github-Resources#61]
Reminder to self:

Looks like at some point https://github.com/ethereum-oasis/baseline-roadmap/issues/51 is going to be using EDI. If/when this occurs, add them to the repo. 

Might also include github language specs: 
https://github.com/freight-trust/edi-tmLanguage

Looks like its only two segments for now.

**Comment by sambacha** [comment]
Hey Michael, appreciate the work you have done documenting the subject, for reference here is the library we are working on for baseline: https://github.com/freight-trust/libinterchange 

At some point I will finish this PR to get EDI recognized on github's linguist: 
https://github.com/freight-trust/linguist-edi

And a rough cut of a Visual Studio Code extension for X12/EDIFACT linting: https://github.com/freight-trust/edizone-vscode

Cheers,

Sam

**Comment by sambacha** [comment]
Almost forgot, here is a new parser from Vanderbilt for Healthcare transactions: https://hiplab.mc.vanderbilt.edu/git/lab/parse-edi

Have a great weekend,

Sam

**Comment by michaelachrisco** [comment]
Thanks @sambacha! Great to hear about these new projects! Im especially excited to see EDI in the syntax highlighting within  GitHub! 

Feel free to add any of the links to the repo if you so desire. I'm not too picky as there isn't a huge amount of code/docs on the subject.
